name: "Icecast"
description: "An icecast2 server with ffmpeg streams hosted"
version: "0.0.4"
slug: "icecast2"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
